---
# version: 1.0.0
# designed to work with Rocky Linux, not tested on any other Linux distro

- hosts: localhost
  tasks:
     - name: disable ipv6 with sysctl
       become: yes
       ansible.posix.sysctl:
         name: "{{ item }}"
         value: "1"
         state: "present"
         reload: "yes"
       with_items:
         - net.ipv6.conf.all.disable_ipv6
         - net.ipv6.conf.default.disable_ipv6
         - net.ipv6.conf.lo.disable_ipv6

     - name: RedHat | placeholder true for ipv6 in modprobe
       become: yes
       ansible.builtin.lineinfile:
         dest: /etc/modprobe.conf
         line: 'install ipv6 /bin/true'
         mode: '0644'
         create: true
       when: ansible_os_family == 'RedHat'

     - name: RedHat | disable ipv6 in sysconfig/network
       become: yes
       ansible.builtin.lineinfile:
         dest: /etc/sysconfig/network
         regexp: "^{{ item.regexp }}"
         line: "{{ item.line }}"
         mode: '0644'
         backup: true
         create: true
       with_items:
         - { regexp: 'NETWORKING_IPV6=.*', line: 'NETWORKING_IPV6=NO' }
         - { regexp: 'IPV6INIT=.*', line: 'IPV6INIT=no' }
       when: ansible_os_family == 'RedHat'

     - name: restart networkmanager service
       become: yes
       ansible.builtin.service:
         name: NetworkManager
         state: restarted
       when: ansible_os_family == 'RedHat'

     - name: rebuild grub
       become: yes
       ansible.builtin.command: "grubby --update-kernel=ALL --args='ipv6.disable=1'"
